name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Six
      id: six
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Six
        setup-command: pip install pygad numpy nbformat matplotlib
        command: python ./grade_homework.py
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        SIX_RESULTS: "${{steps.six.outputs.result}}"
      with:
        runners: six